-- 코드를 입력하세요
SELECT DATE_FORMAT(NF.SALES_DATE, '%Y-%m-%d'), NF.PRODUCT_ID, NF.USER_ID, NF.SALES_AMOUNT 
FROM (SELECT SALES_DATE,PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE 
UNION ALL 
SELECT SALES_DATE,PRODUCT_ID,NULL as USER_ID,SALES_AMOUNT FROM OFFLINE_SALE) NF 
WHERE YEAR(NF.SALES_DATE) = 2022 AND MONTH(NF.SALES_DATE) = 3
ORDER BY NF.SALES_DATE ASC, NF.PRODUCT_ID ASC, NF.USER_ID ASC;
