-- 코드를 입력하세요
SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME 
FROM ANIMAL_OUTS AO, ANIMAL_INS AI 
WHERE AO.ANIMAL_ID = AI.ANIMAL_ID AND (AO.SEX_UPON_OUTCOME LIKE 'Spayed%' OR AO.SEX_UPON_OUTCOME LIKE 'Neutered%') AND AI.SEX_UPON_INTAKE LIKE 'Intact%' 
ORDER BY AO.ANIMAL_ID;