-- 코드를 입력하세요
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI
INNER JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVOR FROM REST_INFO GROUP BY FOOD_TYPE) RI2
ON RI.FOOD_TYPE = RI2.FOOD_TYPE AND RI.FAVORITES = RI2.FAVOR
ORDER BY RI.FOOD_TYPE DESC