SELECT UDU.USER_ID, UDU.NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER UDU
JOIN USED_GOODS_BOARD UGB ON UDU.USER_ID = UGB.WRITER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY UDU.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;