-- 코드를 입력하세요
SELECT FO.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FO.AMOUNT * FP.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT FP, FOOD_ORDER FO 
WHERE FP.PRODUCT_ID = FO.PRODUCT_ID AND MONTH(PRODUCE_DATE) = 5 
GROUP BY FO.PRODUCT_ID  
ORDER BY SUM(FO.AMOUNT * FP.PRICE) DESC, FO.PRODUCT_ID;